DOCSP-45206 Atlas Search Indexes
mongodb/docs-ruby pull request #113
Opened 2024-12-20 01:58 UTC by lindseymoore

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-golang/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-NNNNN>

### Staging Links

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-12-20 20:54 UTC, jamis requested changes
As mentioned in slack, the Ruby driver has a dedicated API for creating, querying, updating, and deleting search indexes. The existing docs are here: https://www.mongodb.com/docs/ruby-driver/current/reference/search-indexes/ -- perhaps they can be of help in this?

2025-01-10 18:58 UTC, lindseymoore commented on source/indexes/atlas-search-index.txt
> +following API documentation:
Are there any API docs to link to for Atlas Search methods?

2025-01-10 21:22 UTC, jamis approved these changes

2025-01-10 21:22 UTC, jamis commented on source/indexes/atlas-search-index.txt
> +following API documentation:
It looks like our API docs are out-of-date. The API docs at https://mongodb.com/docs/ruby-driver/current/api/ are for driver version 2.19, which predates the search index API. I don't know that I've ever seen how we update those API docs; I'll dig around and see what I can find out.

2025-01-13 18:10 UTC, lindseymoore commented on source/indexes/atlas-search-index.txt
> +following API documentation:
Thank you for checking @jamis! Please let me know if the API docs; otherwise; I will delete this section.

2025-01-13 19:15 UTC, rachel-mack approved these changes
Just missing a space:

2025-01-13 19:15 UTC, rachel-mack commented on source/indexes/atlas-search-index.txt
> +the index you want to update by using either the``name`` or ``id`` of the index.
```suggestion
the index you want to update by using either the ``name`` or ``id`` of the index. 
```

2025-01-13 20:44 UTC, lindseymoore commented on source/includes/indexes/atlas-search-index.rb
> +index-definition = {
```suggestion
index_definition = {
```

2025-01-16 15:53 UTC, merged